In [ ]:
cube = lambda x: x**3  # complete the lambda function

def fibonacci(n):
    # return a list of fibonacci numbers
    if n == 0:
        return []
    elif n == 1:
        return [0]
    fib = [0, 1]
    for i in range(2, n):
        fib.append(fib[i-1] + fib[i-2])
    return fib

if __name__ == '__main__':
    n = int(input())
    print(list(map(cube, fibonacci(n))))

In [5]:
def removeSpecialCharacters(strParam: str) -> str:
    return ' '.join(e for e in strParam if e.isalnum() or e == '_' or e == '-')
print(removeSpecialCharacters("strParam = 'Nora Rahaf$'")) 

s t r P a r a m N o r a R a h a f


In [1]:
print('hello world')

hello world


In [5]:
import numpy

my_array = numpy.array([1.1, 2.2, 3.3, 4.4, 5.5, 6.6, 7.7, 8.8, 9.9])
my_array = my_array.astype(int)
print (my_array.astype(float))       #[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]


[1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [4]:
my_array = numpy.array([1.1, 2.2, 3.3, 4.4, 5.5, 6.6, 7.7, 8.8, 9.9])
print numpy.ceil(my_array)          #[  2.   3.   4.   5.   6.   7.   8.   9.  10.]

SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)? (2455708189.py, line 2)

In [6]:
my_array = numpy.array([1.1, 2.2, 3.3, 4.4, 5.5, 6.6, 7.7, 8.8, 9.9])
print numpy.rint(my_array)          #[  1.   2.   3.   4.   6.   7.   8.   9.  10.]

SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)? (191255361.py, line 2)

In [11]:
# Input Format

# A single line of input containing the space separated elements of array

# .

# Output Format

# On the first line, print the
# of A.
# On the second line, print the of A.
# On the third line, print the of A.

# Sample Input

# 1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9

# Sample Output

# [ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
# [  2.   3.   4.   5.   6.   7.   8.   9.  10.]
# [  1.   2.   3.   4.   6.   7.   8.   9.  10.]

inputs = "1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9"
my_array = numpy.array(inputs.split(), float)
print((my_array.astype(int)).astype(float))
print (numpy.ceil(my_array), end=" ")
print (numpy.rint(my_array), end=" ")



[1. 2. 3. 4. 5. 6. 7. 8. 9.]
[ 2.  3.  4.  5.  6.  7.  8.  9. 10.]
[ 1.  2.  3.  4.  6.  7.  8.  9. 10.]
