In [ ]:
cube = lambda x: x**3  # complete the lambda function

def fibonacci(n):
    # return a list of fibonacci numbers
    if n == 0:
        return []
    elif n == 1:
        return [0]
    fib = [0, 1]
    for i in range(2, n):
        fib.append(fib[i-1] + fib[i-2])
    return fib

if __name__ == '__main__':
    n = int(input())
    print(list(map(cube, fibonacci(n))))

In [25]:
def max_element(arr: list[int]) -> int:
    return sorted(arr)[-1]

print(max_element([1,1,1,2,3,2]))

3


In [37]:
def cumulative_sum(arr: list[int]) -> list[int]:
    return [i+arr[x-1] if x != 0 else i for x,i in enumerate(arr)]

In [39]:
arr = [2, 4, 8]

print(cumulative_sum(arr))

[2, 6, 14]


In [3]:
def cap_space(txt: str) -> str:
    return ''.join([' ' + i.lower() if i.isupper() else i for i in txt])

In [4]:
cap_space('wePlayTennis')

'w e  p l a y  t e n n i s'

In [5]:
def middle_char(word: str) -> str:
    if len(word) <= 2:
        return word
    len1 = int(len(word)/2)
    if len(word)%2==0:
        return word[len1-1:len1+1]
    return word[len1]

In [6]:
word = 'salem'
print(middle_char(word))

l


In [21]:
from typing import List
def find_prefix(words: List[str], text: str) -> List[str]:
    lst=[]
    for i in words:
        if i.lower().startswith(text.lower()):
            lst.append(i)
    return lst if lst else ['No matches found']

In [23]:
words = ['Save', 'Saudi', 'Satr', 'Send', 'Salt', 'Super', 'Sample']
text = 'sda'

print(find_prefix(words,text))

['No matches found']


In [13]:
# Define a lambda function to cube a number
def fibonacci(n, fib=[0, 1]):
    # Return a list of fibonacci numbers in a recursive way
    if n <= len(fib):
        # If the requested length is less than or equal to the current list length, return the list up to n elements
        return fib[:n]
    else:
        # Otherwise, append the next Fibonacci number to the list
        fib.append(fib[-1] + fib[-2])
        # Recursively call the function until the list is of length n
        return fibonacci(n, fib)

if __name__ == '__main__':
    # Read an integer input from the user
    n = int(input())
    # Print the list of cubed Fibonacci numbers
    print(list((fibonacci(n))))


[0, 1]


In [ ]:
cube = lambda x: x**3 
mylist = []

def fibonacci(n):
    if n <= 1:
        mylist.append(n)
        return mylist
    else:
       return fibonacci(n-1) + fibonacci(n-2)

n = int(input())
print(fibonacci(8))

In [5]:
import numpy

my_array = numpy.array([1.1, 2.2, 3.3, 4.4, 5.5, 6.6, 7.7, 8.8, 9.9])
my_array = my_array.astype(int)
print (my_array.astype(float))       #[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]


[1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [4]:
my_array = numpy.array([1.1, 2.2, 3.3, 4.4, 5.5, 6.6, 7.7, 8.8, 9.9])
print numpy.ceil(my_array)          #[  2.   3.   4.   5.   6.   7.   8.   9.  10.]

SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)? (2455708189.py, line 2)

In [6]:
my_array = numpy.array([1.1, 2.2, 3.3, 4.4, 5.5, 6.6, 7.7, 8.8, 9.9])
print numpy.rint(my_array)          #[  1.   2.   3.   4.   6.   7.   8.   9.  10.]

SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)? (191255361.py, line 2)

In [11]:
# Input Format

# A single line of input containing the space separated elements of array

# .

# Output Format

# On the first line, print the
# of A.
# On the second line, print the of A.
# On the third line, print the of A.

# Sample Input

# 1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9

# Sample Output

# [ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
# [  2.   3.   4.   5.   6.   7.   8.   9.  10.]
# [  1.   2.   3.   4.   6.   7.   8.   9.  10.]

inputs = "1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9"
my_array = numpy.array(inputs.split(), float)
print((my_array.astype(int)).astype(float))
print (numpy.ceil(my_array), end=" ")
print (numpy.rint(my_array), end=" ")



[1. 2. 3. 4. 5. 6. 7. 8. 9.]
[ 2.  3.  4.  5.  6.  7.  8.  9. 10.]
[ 1.  2.  3.  4.  6.  7.  8.  9. 10.]
